version: '2.3'
services:
  master:
    image: sawyer_train:latest
    runtime: nvidia
    environment: 
      - "DISPLAY=$DISPLAY"
      - "CUDA_VISIBLE_DEVICES=3"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./mjkey/mjkey.txt:/root/.mujoco/mjkey.txt
      - ./code/:/root/code/
      - ./robosuite/:/root/robosuite/
      - ./stable-baselines/:/root/stable-baselines/
    command: bash -c "cd stable-baselines 
                      && pip3 install --no-dependencies -e . 
                      && cd ../code && bash" 
    tty: true
    stdin_open: true
