version: '2.3'
services:
  master:
    image: sawyer_train:latest
    environment: 
      - "DISPLAY=$DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./mjkey/mjkey.txt:/root/.mujoco/mjkey.txt
      - ./code/:/root/code/
      - ./robosuite/:/root/robosuite/
    tty: true
    stdin_open: true
