version: '2.3'
services:
  master:
    image: crl_sawyer
    runtime: nvidia
    environment: 
      - "DISPLAY=$DISPLAY"
      - "CUDA_VISIBLE_DEVICES=2"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./mjkey/mjkey.txt:/root/.mujoco/mjkey.txt
      - ./code/:/root/code/
      - ./robosuite/:/root/robosuite/
      - ./stable-baselines/:/root/stable-baselines/
    tty: true
    stdin_open: true
    command: /bin/bash
